### ISSUE TITLE
Bottleneck feature vector size

### ISSUE THREAD

**Issue by spectralnanodiamond** [ctr26/bioimage_embed#2]
It would be great to have bottleneck feature vector size of the VAE to be an accessible parameter. This would be help it be changed so that it was reasonable compared to the input patch size. 

As part of this it may be necessary to have number of layers increase or decrease to keep the VAE network contraction and then expansion smooth. This could be another parameter, or calculated automatically.

**Comment by ctr26** [comment]
https://github.com/ctr26/bio_vae/pull/3

Adding pythae compatibility which gives you easier access to latent space size

**Comment by ctr26** [comment]
Resolved for most models pythae and legacy
